trigger:
  branches:
    include:
      - main

stages:
- stage: validate
  jobs:
  - job: tf_validate
    pool:
      name: default
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.7'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        backendServiceArm: ''
        backendAzureRmResourceGroupName: 'terraform-state-rg'
        backendAzureRmStorageAccountName: 'tfdevbackendabdul'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'

- stage: Dev_deploy
  dependsOn: validate
  condition: succeeded()

  jobs:
  - job: terraform_apply_dev
    pool:
      name: default
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.7'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        backendServiceArm: ''
        backendAzureRmResourceGroupName: 'terraform-state-rg'
        backendAzureRmStorageAccountName: 'tfdevbackendabdul'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'dev.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        commandOptions: '-var-file=terraform.tfvars --auto-approve'
        environmentServiceNameAzureRM: ''

- stage: Stage_deploy
  dependsOn: Dev_deploy
  condition: succeeded()

  jobs:
  - job: terraform_apply_stage
    pool:
      name: default
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.7'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/staging'
        backendServiceArm: ''
        backendAzureRmResourceGroupName: 'terraform-state-rg'
        backendAzureRmStorageAccountName: 'tfstagebackendabdul'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'stage.tfstate'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/staging'
        commandOptions: '-var-file=terraform.tfvars --auto-approve'
        environmentServiceNameAzureRM: ''